title: Zhihao Deng's Homepage
page-top-title: Zhihao Deng
top-section-bg-text: Data Science
home-subtitle: Zhihao Deng&ensp;|&ensp;邓志豪
copyright-text: '&copy; Zhihao Deng 2025-2026. All Rights Reserved.'
